### ISSUE TITLE
How to use test script to test locally 

### ISSUE THREAD

**Issue by sudhanshuptl** [rchukh/presto-querylog#3]

**Comment by rchukh** [comment]
Just follow the [build](https://github.com/rchukh/presto-querylog#build) and [deploy](https://github.com/rchukh/presto-querylog#deploy) parts of the README file, and the logs will be exactly where you specified during the [Prepare configuration file](https://github.com/rchukh/presto-querylog#create-log4j2-configuration-file) part.

**Comment by sudhanshuptl** [comment]
Thanks , this is script was very helpful
