### ISSUE TITLE
Event listener presto-querylog is not registered

### ISSUE THREAD

**Issue by agupta94** [rchukh/presto-querylog#9]
Hi! Thanks for responding quickly and fixing the ClassNotFoundException! I am getting the following error now -
`2019-07-31T15:47:40.109Z	ERROR	main	com.facebook.presto.server.PrestoServer	Event listener presto-querylog is not registered java.lang.IllegalStateException: Event listener presto-querylog is not registered at com.google.common.base.Preconditions.checkState(Preconditions.java:585) at com.facebook.presto.eventlistener.EventListenerManager.setConfiguredEventListener(EventListenerManager.java:81) at com.facebook.presto.eventlistener.EventListenerManager.loadConfiguredEventListener(EventListenerManager.java:68) at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:144) at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:73)`

Could you please help me with this? Thanks!

**Comment by rchukh** [comment]
@agupta94 
It looks like the original Presto distribution from Facebook is being used. This one - http://prestodb.github.io/

Just recently (2 days ago) - I have updated this plugin to be used with Presto distribution from PrestoSQL foundation - https://prestosql.io

---

If you want to use the Facebook version - you may try to use this commit, as it was the latest one that worked with it.
https://github.com/rchukh/presto-querylog/commit/e5f512442e31bd830c92c218cbc312f5b0a88730

But going forward I plan to base this plugin only on the PrestoSQL foundation version.

**Comment by agupta94** [comment]
So if I update my setup for presto server to be installed from PrestoSQL foundation, the plugin should work automatically?

**Comment by agupta94** [comment]
Ahh I see. I'll try to use that commit, or update my presto distribution.
